plugins {
    alias(libs.plugins.spring.boot)
    alias(libs.plugins.jib)
}

dependencies {
    implementation project(':platform:platform-core')
    implementation project(':platform:platform-events')
    implementation project(':platform:platform-security')
    implementation project(':platform:platform-observability')

    implementation libs.bundles.web.service
    implementation libs.bundles.kafka
    implementation libs.bundles.azure
    implementation libs.lombok

    testImplementation project(':platform:platform-test')
    testImplementation libs.testcontainers.kafka
}

jib {
    from { image = 'eclipse-temurin:21-jre-alpine' }
    to   { image = "${System.getenv('CONTAINER_REGISTRY') ?: 'modusacr.azurecr.io'}/usage-metering:${project.version}" }
    container {
        jvmFlags = ['-XX:+UseZGC', '-XX:+ZGenerational', '--enable-preview', '-Djava.security.egd=file:/dev/./urandom']
        ports    = ['8089']
        labels   = [version: project.version, service: 'usage-metering']
    }
}
